language: node_js
sudo: required
dist: trusty
node_js: '10'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_script:
- npm run build
script:
- xvfb-run wct --npm
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'windows 10/microsoftedge@15' -s 'macos 10.12/safari@10' -s 'windows 8.1/internet explorer@11' --npm; fi
env:
  global:
  - secure: mNT4DpaOzcY+Z8JmXhVdbYBRt1gJG7kVMfe0Kd3HSRwQwAltW1JWhnRWQgW526xi/EFuYkIy1Ec4Hhc0pZ+t+ngXrHgtVPV6te7nQzBhBUNFZv72nDagk8YxQBTcSHMEVRa7c4NXlCW66hM0WWDVy7PACs7NuGj25qegFUulbjNEmYfwF8VMsfyB8/X6NJff8ZQTWEACwODJIBY2l0ogxI2jbUjTnrVNvtjd4IV1gnmi2AvY0RwRs/grigP4oMPcD/5tleUBjlojqq3U/DjMCoaoCge7fPnRZ2O1GHVHPOlAlFWa6DGvsXBiPNqlzchAQtkCKCnNJ1xM8UNlR0EYQCWBSsXO+wmAFoB1UexumHObsaCzLTL2yYXByCzKVNlGkCMppZUp+b+T3Vu039TEF1dCXf4XpQOouNb9pdlR0tkWUOF08hENzeAkHBFO1nw3kt+smm/b/6QXHe0H+X2GN3uKRX/TMYYgR3cckD4cQ9DeaXlJ/6tJtoVkOyNLL1LOHVtS7MTL2oUBJnj29cjOaUoCg/aVEt+g7brysj8Eb7itZctc/GwL/cWqIIKCuUUAuRJYgrBx3AQH9GjMtNAsrMtoVEmcOIK1lBLLmeduZXDogTevTMbGtyToATAQbLX/a2TxUBM5AZLE/dMiUnmZMVEMZ4anp2VhrmzflrbRcBI=
  - secure: UMzIg/aYKoDeMQqDyXcxpX0a1gWwmtCo+tx1zF0xhyoEPz3DNNV7axdqnqhiU9jPf7T5mGK4WWNDYWeFKMooD9J2rCgSxOPZHNDpcwQlC7KNHMKHXlMPLDzh1XborrSABowwj+Osq2Nmy7u1+aRtJDpcZ/PrYpsdHOx1wp+8aeO7ho8IFtgtDbdoQ7NUHXA4JtmORq4DH5MFyetrU70JSjwziL1T7H3kHkstjptMx4b5VszepcwFqsYXX+l0LxD1xYPcSc0QanwThYJLJb1JQSkqaDVphrMo+p7XdDVva9ExXvWfMOwJDRBvYP24sqBcYHei78irCzMKnRrcENgSK7G185p+9v5eO7DPROw5jjBB+uxXO/B5C1j1D5I1I1AMeccZ8kaBlqJgxhtTha9fJkwiRzYBrgmSS6eTORWMClAY84RlOtB2pL6wkx+/3ffXqbfbSP/mstAF1VkGwfav/XaWp2kxI4prEJi45PR4+wigugLQB/pLvMdItfGxAJLs+npv+w5nM7I2hJVfwvbuPVtAlz9pcn70kHcMvQbXsmdUzV6Se467HuwtruVQEhE6X01AW35VHLQi1GBMG/0xird+6WFi26/zj08nZaetW6BKqodHVYmzrSs5L2OcelJmAOOY2JQwQO/7RJ6zzwWu5hNdAo8STDgyYRhbYFlTRjs=
