name: Benchmarks

on: [pull_request]

jobs:
  benchmarks:
    # Don't run on forks. Benchmarks can't run on forks because secrets aren't
    # available, which are needed for posting result comments.
    if: github.repository == 'lit/lit'

    name: benchmarks

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: NPM install
        run: npm ci

      - name: Build
        run: npm run build

      # lit-html:kitchen-sink
      - name: Benchmark lit-html/kitchen-sink
        run: |
          cd packages/benchmarks
          npx tachometer \
            --config lit-html/kitchen-sink/tachometer.json \
            --json-file lit-html/kitchen-sink/results.json

      - name: Report lit-html-kitchen-sink
        uses: andrewiggins/tachometer-reporter-action@v2
        with:
          report-id: lit-html-kitchen-sink
          path: packages/benchmarks/lit-html/kitchen-sink/results.json
          pr-bench-name: this-change
          base-bench-name: tip-of-tree

      # lit-html:template-heavy
      - name: Benchmark lit-html/template-heavy
        run: |
          cd packages/benchmarks
          npx tachometer \
            --config lit-html/template-heavy/tachometer.json \
            --json-file lit-html/template-heavy/results.json

      - name: Report lit-html-template-heavy
        uses: andrewiggins/tachometer-reporter-action@v2
        with:
          report-id: lit-html-template-heavy
          path: packages/benchmarks/lit-html/template-heavy/results.json
          pr-bench-name: this-change
          base-bench-name: tip-of-tree

      # lit-html:repeat
      - name: Benchmark lit-html/repeat
        run: |
          cd packages/benchmarks
          npx tachometer \
            --config lit-html/repeat/tachometer.json \
            --json-file lit-html/repeat/results.json

      - name: Report lit-html-repeat
        uses: andrewiggins/tachometer-reporter-action@v2
        with:
          report-id: lit-html-repeat
          path: packages/benchmarks/lit-html/repeat/results.json
          pr-bench-name: this-change
          base-bench-name: tip-of-tree

      # lit-element:list
      - name: Benchmark lit-element/list
        run: |
          cd packages/benchmarks
          npx tachometer \
            --config lit-element/list/tachometer.json \
            --json-file lit-element/list/results.json

      - name: Report lit-element-list
        uses: andrewiggins/tachometer-reporter-action@v2
        with:
          report-id: lit-element-list
          path: packages/benchmarks/lit-element/list/results.json
          pr-bench-name: this-change
          base-bench-name: tip-of-tree

      # reactive-element:list
      - name: Benchmark reactive-element/list
        run: |
          cd packages/benchmarks
          npx tachometer \
            --config reactive-element/list/tachometer.json \
            --json-file reactive-element/list/results.json

      - name: Report reactive-element-list
        uses: andrewiggins/tachometer-reporter-action@v2
        with:
          report-id: reactive-element-list
          path: packages/benchmarks/reactive-element/list/results.json
          pr-bench-name: this-change
          base-bench-name: tip-of-tree
