name: Benchmarks

on: [pull_request]

jobs:
  benchmarks:
    name: benchmarks

    # We can't currently run benchmarks on PRs from forked repos, because the
    # tachometer action reports results by posting a comment, and we can't post
    # comments without a github token.
    if: github.event.pull_request == null || github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Restore node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          # Bump the number after `lit-1.x-node-modules` to force a cache
          # update. Note there are multiple cache actions in `tests.yml` that
          # should all keep keys in sync.
          key: lit-1.x-node-modules-0-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: NPM install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Benchmark
        run: npx tach --config tachometer.json --json-file results.json

      - name: Report
        uses: andrewiggins/tachometer-reporter-action@v2
        with:
          report-id: lit-html-1.x
          path: results.json
          pr-bench-name: this-change
          base-bench-name: lit-html-1.x
