name: Benchmarks

on: [pull_request]

jobs:
  benchmarks:
    name: benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Benchmark lit-html/kitchen-sink
        run: |
          cd packages/benchmarks
          npx tachometer \
            --config lit-html/kitchen-sink/tachometer.json \
            --json-file lit-html/kitchen-sink/results.json

      - name: Report lit-html-kitchen-sink
        uses: andrewiggins/tachometer-reporter-action@v1
        with:
          report-id: lit-html-kitchen-sink
          path: packages/benchmarks/lit-html/kitchen-sink/results.json
          pr-bench-name: this-change
          base-bench-name: tip-of-tree

      - name: Benchmark lit-element/stub1
        run: |
          cd packages/benchmarks
          npx tachometer \
            --config lit-element/stub1/tachometer.json \
            --json-file lit-element/stub1/results.json

      - name: Report lit-element-stub1
        uses: andrewiggins/tachometer-reporter-action@v1
        with:
          report-id: lit-element-stub1
          path: packages/benchmarks/lit-element/stub1/results.json
          pr-bench-name: this-change
          base-bench-name: tip-of-tree
