name: Generate Release Image

on:
  pull_request:
    paths:
      - '**/CHANGELOG.md'

jobs:
  release-image:
    if: github.repository == 'lit/lit'

    name: Generate Release Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: NPM install
        run: npm ci

      - name: Build release-image script
        working-directory: packages/internal-scripts
        run: npm run build

      - name: Create release image
        run: |
          # Store the PR body contents containing the changelog in 'release.md'
          cat <<'EOF' > release.md
          ${{ github.event.pull_request.body }}
          EOF
          # Only render the pull request content including and after the "#
          # Releases" heading.
          node_modules/.bin/release-image -m <(sed -n '/# Releases/,$p' release.md)

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: releaseimage
          path: release.png
