name: Sync Starter Kits

on:
  push:
    branches:
      - main

jobs:
  starter-kits:
    # Don't run on forks. We can and should only release from the main repo.
    if: github.repository == 'lit/lit'

    name: Sync Starter Kits
    runs-on: ubuntu-latest
    steps:
      - name: Use Lit Robot's name and email for all git actions
        run: |
          git config --global user.name "Lit Robot"
          git config --global user.email "lit-robot@google.com"

      - name: Checkout Lit Repo
        uses: actions/checkout@v2
        with:
          path: lit

      - name: Sync lit-element-starter-ts repo
        uses: ./.github/workflows/sync-package.yaml
        with:
          source-repo-path: lit
          source-package-path: packages/lit-starter-ts
          destination-checkout-path: lit-element-starter-ts
          destination-repo: lit/lit-element-starter-ts
          destination-branch: release-automation-test-main
          destination-token: ${{ secrets.LIT_ROBOT_AUTOMATION_PAT }}

      - name: Sync lit-element-starter-js repo
        uses: ./.github/workflows/sync-package.yaml
        with:
          source-repo-path: lit
          source-package-path: packages/lit-starter-js
          destination-checkout-path: lit-element-starter-js
          destination-repo: lit/lit-element-starter-js
          destination-branch: release-automation-test-main
          destination-token: ${{ secrets.LIT_ROBOT_AUTOMATION_PAT }}
