name: Tests

on: [push, pull_request]

jobs:
  changeset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          # Note: we do not cache here because we're not running lerna
          # bootstrap, so the ~/.npm dir won't have all dependencies, and if
          # this job finishes first then that's all we'll cache.

      - run: git checkout main
      - run: git checkout ${{ github.sha }}
      - run: npm ci
      - run: npm run changeset status -- --since=main

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          # Note: we do not cache here because we're not running lerna
          # bootstrap, so the ~/.npm dir won't have all dependencies, and if
          # this job finishes first then that's all we'll cache.

      - run: npm ci
      - run: npm run lint

  tests-local:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Installs system dependencies needed for playwright.
      - uses: microsoft/playwright-github-action@v1

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Test
        env:
          BROWSERS: preset:local
          CONCURRENT_BROWSERS: 3
        run: npm run test

  tests-sauce:
    # We can't run Sauce tests on PRs from forked repos, since they don't have
    # access to secrets.
    if: github.event.pull_request == null || github.event.pull_request.head.repo.full_name == github.repository

    # Sauce tests are still unreliable. Run them, but don't mark a commit as
    # failing if it fails.
    continue-on-error: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Installs system dependencies needed for playwright.
      - uses: microsoft/playwright-github-action@v1

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          BROWSERS: preset:sauce
          # TODO We should be able to bump this up, but going above 2 currently
          # causes flakiness where the second test job (dev vs prod) fails to
          # set up the Sauce tunnel (maybe something to do with browsers still
          # shutting down on the Sauce VM from the previous run?).
          CONCURRENT_BROWSERS: 2
        run: npm run test

  tests-sauce-ie11:
    # We can't run Sauce tests on PRs from forked repos, since they don't have
    # access to secrets.
    if: github.event.pull_request == null || github.event.pull_request.head.repo.full_name == github.repository

    # Sauce tests are still unreliable. Run them, but don't mark a commit as
    # failing if it fails.
    continue-on-error: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Installs system dependencies needed for playwright.
      - uses: microsoft/playwright-github-action@v1

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          BROWSERS: preset:sauce-ie11
          CONCURRENT_BROWSERS: 1
        run: npm run test
