name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      # Note this is the way to set an environment variable that lives across
      # all steps
      # (https://docs.github.com/en/actions/reference/environment-variables#about-environment-variables).
      - name: Set environment variables
        run: echo "::set-env name=PLAYWRIGHT_BROWSERS_PATH::$HOME/.playwright"

      # Cache all of our node_modules/ directories and playwright browser
      # binaries to save ~30 seconds of install time.
      - name: Restore node_modules/playwright
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: npm-playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      # Installs system dependencies needed for playwright. Not sure how to
      # cache this.
      - uses: microsoft/playwright-github-action@v1

      - name: NPM install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lerna bootstrap
        if: steps.cache.outputs.cache-hit != 'true'
        # Don't install concurrently because if multiple playwright postinstall
        # scripts are running at the same time, they will frequently collide and
        # crash. See https://github.com/microsoft/playwright/issues/3912.
        run: npm run bootstrap -- --concurrency=1

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
