name: Build in TSC 3.4

on: [push, pull_request]


jobs:
  build_old:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: NPM install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install typescript@~3.4
        run: npm install typescript@~3.4

      - name: Print TypeScript version
        run: npx tsc --version

      - name: Type check .d.ts files
        run: npx tsc ts3.4/lit-html.d.ts ts3.4/directives/*.d.ts --noEmit -t esnext --moduleResolution Node
